follows = {
    "PROGRAM": ["$"],
    "BODY": ["!end"],
    "DECLARE": ["{"],
    "IDENTIFIERS": [":"],
    "TYPES": [";"],
    "DEFAULT": [";"],
    "MAIN": ["!end"],
    "STATEMENT": [";"],
    "EXPRESION": ["}", "for", "do", "then"],
    "EXI": ["=", "<", ">", "<=", ">=", "!="],
    "EXP": ["}", "for", "do", "then", "=", "<", ">", "<=", ">=", "!="],
    "REL": ["+", "-", "||", "{", "identifier", "true", "string", "number"],
    "ASIGN": ["}", ";"],
    "TERM": ["}", "for", "do", "then", "=", "<", ">", "<=", ">=", "!="],
    "RIL": ["}", "for", "do", "then", "=", "<", ">", "<=", ">=", "!="],
    "FACTOR": ["}", "for", "do", "then", "=", "<", ">", "<=", ">=", "!="],
    "STATEMENTS": ["}"],
    "FOR STAT": [],
    "CONTER": ["do"],
    "WHILE STAT": [],
    "INPUT": [],
    "ROS": [],
    "OUTPUT": [],
    "IF STAT": [],
    "ELSE": ["!endif"],
    "ROT": ["do"]
}