predictiveMatrix = {
    "PROGRAM": {"!init": ["!init", "identifier", ";", "BODY", "¡end"]},
    "BODY": {"var": ["DECLARE", "MAIN"], "{": ["MAIN"]},
    "DECLARE": {"var": ["var", "IDENTIFIERS", ":", "TYPES", ";"]},
    "IDENTIFIERS": {"identifier": ["identifier", ";", "IDENTIFIERS'"]},
    "IDENTIFIERS'": {
        "identifier": ["identifier", ";", "IDENTIFIERS'"],
        ":": ["epsilon"],
    },
    "TYPES": {
        "integer": ["DEFAULT"],
        "decimal": ["DEFAULT"],
        "string": ["DEFAULT"],
        "bool": ["DEFAULT"],
    },
    "DEFAULT": {
        "integer": ["integer"],
        "decimal": ["decimal"],
        "string": ["string"],
        "bool": ["bool"],
    },
    "MAIN": {"{": ["{", "STATEMENTS", "}"]},
    "STATEMENT": {
        "identifier": ["ASIGN"],
        "for": ["FOR STAT"],
        "while": ["WHILE STAT"],
        "read": ["INPUT"],
        "write": ["OUTPUT"],
        "if": ["IF STAT"],
    },
    "EXPRESION": {
        "identifier": ["EXP", "EXPRESION'"],
        "true": ["EXP", "EXPRESION'"],
        "string": ["EXP", "EXPRESION'"],
        "number": ["EXP", "EXPRESION'"],
        "{": ["EXP", "EXPRESION'"],
        "+": ["EXP", "EXPRESION'"],
        "-": ["EXP", "EXPRESION'"],
    },
    "EXPRESION'": {
        "<": ["REL", "EXP"],
        "<=": ["REL", "EXP"],
        "=": ["REL", "EXP"],
        ">": ["REL", "EXP"],
        ">=": ["REL", "EXP"],
        "!=": ["REL", "EXP"],
        "||": ["REL", "EXP"],
        ";": ["epsilon"],
        "do": ["epsilon"],
        "then": ["epsilon"],
        "}": ["epsilon"],
    },
    "REL": {
        "<": ["<"],
        "<=": ["<="],
        "=": ["="],
        ">": [">"],
        ">=": [">="],
        "!=": ["!="],
        "||": ["||"],
    },
    "EXP": {
        "identifier": ["TERM", "EXP'"],
        "true": ["TERM", "EXP'"],
        "string": ["TERM", "EXP'"],
        "number": ["TERM", "EXP'"],
        "{": ["TERM", "EXP'"],
        "+": ["TERM", "EXP'"],
        "-": ["TERM", "EXP'"],
    },
    "EXP'": {
        "+": ["+", "TERM", "EXP'"],
        "-": ["-", "TERM", "EXP'"],
        ";": ["epsilon"],
        "do": ["epsilon"],
        "then": ["epsilon"],
        "}": ["epsilon"],
        "<": ["epsilon"],
        "<=": ["epsilon"],
        "=": ["epsilon"],
        ">": ["epsilon"],
        ">=": ["epsilon"],
        "!=": ["epsilon"],
        "||": ["epsilon"],
    },
    "ASIGN": {"identifier": ["identifier", "=", "EXPRESION"]},
    "TERM": {
        "identifier": ["FACTOR", "TERM'"],
        "true": ["FACTOR", "TERM'"],
        "string": ["FACTOR", "TERM'"],
        "number": ["FACTOR", "TERM'"],
        "{": ["FACTOR", "TERM'"],
    },
    "TERM'": {
        "*": ["*", "FACTOR", "TERM'"],
        "/": ["/", "FACTOR", "TERM'"],
        "&&": ["&&", "FACTOR", "TERM'"],
        "+": ["epsilon"],
        "-": ["epsilon"],
        ";": ["epsilon"],
        "do": ["epsilon"],
        "then": ["epsilon"],
        "}": ["epsilon"],
        "<": ["epsilon"],
        "<=": ["epsilon"],
        "=": ["epsilon"],
        ">": ["epsilon"],
        ">=": ["epsilon"],
        "!=": ["epsilon"],
        "||": ["epsilon"],
    },
    "FACTOR": {
        "{": ["{", "EXPRESION", "}"],
        "identifier": ["identifier"],
        "true": ["true"],
        "string": ["string"],
        "number": ["number"],
    },
    "STATEMENTS": {
        "identifier": ["STATEMENT", ";", "STATEMENTS'"],
        "for": ["STATEMENT", ";", "STATEMENTS'"],
        "while": ["STATEMENT", ";", "STATEMENTS'"],
        "read": ["STATEMENT", ";", "STATEMENTS'"],
        "write": ["STATEMENT", ";", "STATEMENTS'"],
        "if": ["STATEMENT", ";", "STATEMENTS'"],
    },
    "STATEMENTS'": {
        "identifier": ["STATEMENT", ";", "STATEMENTS'"],
        "for": ["STATEMENT", ";", "STATEMENTS'"],
        "while": ["STATEMENT", ";", "STATEMENTS'"],
        "read": ["STATEMENT", ";", "STATEMENTS'"],
        "write": ["STATEMENT", ";", "STATEMENTS'"],
        "if": ["STATEMENT", ";", "STATEMENTS'"],
        "}": ["epsilon"],
        "endif": ["epsilon"],
    },
    "FOR STAT": {"for": ["for", "CONTER", "do", "{", "STATEMENTS", "}"]},
    "CONTER": {"identifier": ["identifier", ":=", "EXPRESION", "for", "ROT"]},
    "WHILE STAT": {"while": ["while", "EXPRESION", "do", "{", "STATEMENTS", "}"]},
    "INPUT": {"read": ["read", "{", "ROS", "}"]},
    "ROS": {"identifier": ["identifier", ",", "ROS"], "}": ["identifier"]},
    "OUTPUT": {"write": ["write", "(", "ROS", ")"]},
    "IF STAT": {
        "if": ["if", "EXPRESION", "then", "{", "STATEMENTS", "}", "ELSE", "endif"]
    },
    "ELSE": {"else": ["else", "{", "STATEMENTS", "}"], "endif": ["epsilon"]},
    "ROT": {
        "identifier": ["EXPRESION"],
        "true": ["EXPRESION"],
        "string": ["EXPRESION"],
        "number": ["EXPRESION"],
        "{": ["EXPRESION"],
        "+": ["EXPRESION"],
        "-": ["EXPRESION"],
    },
}
