firsts = {
    "PROGRAM": ["¡init"],
    "BODY": ["var", "{"],
    "DECLARE": ["var"],
    "DECLARE'": ["var", "epsilon"],
    "IDENTIFIERS": ["identifier"],
    "IDENTIFIERS'": ["identifier", "epsilon"],
    "TYPES": ["integer", "decimal", "string", "bool"],
    "DEFAULT": ["integer", "decimal", "string", "bool"],
    "MAIN": ["{"],
    "STATEMENT": ["identifier", "for", "while", "read", "write", "if"],
    "EXPRESION": ["identifier", "true", "string", "number", "{", "+", "-"],
    "EXPRESION'": ["<", "<=", "=", ">", ">=", "!=", "||", "epsilon"],
    "REL": ["<", "<=", "=", ">", ">=", "!=", "||"],
    "EXP": ["identifier", "true", "string", "number", "{", "+", "-"],
    "EXP'": ["+", "-", "epsilon"],
    "ASIGN": ["identifier"],
    "TERM": ["identifier", "true", "string", "number", "{"],
    "TERM'": ["*", "/", "&&", "epsilon"],
    "FACTOR": ["{", "identifier", "true", "string", "number"],
    "STATEMENTS": ["identifier", "for", "while", "read", "write", "if"],
    "STATEMENTS'": ["identifier", "for", "while", "read", "write", "if", "epsilon"],
    "FOR STAT": ["for"],
    "CONTER": ["identifier"],
    "WHILE STAT": ["while"],
    "INPUT": ["read"],
    "ROS": ["identifier"],
    "OUTPUT": ["write"],
    "IF STAT": ["if"],
    "ELSE": ["else", "epsilon"],
    "ROT": ["identifier", "true", "string", "number", "{", "+", "-"]
    }