follows = {
    "PROGRAM": ["$"],
    "BODY": ["¡end"],
    "DECLARE": ["{"],
    "DECLARE'": ["{"],
    "IDENTIFIERS": [":"],
    "IDENTIFIERS'": [":"],
    "TYPES": [";"],
    "DEFAULT": [";"],
    "MAIN": ["¡end"],
    "STATEMENT": [";"],
    "EXPRESION": [";", "do", "then", "}"],
    "EXPRESION'": [";", "do", "then", "}"],
    "REL": ["identifier", "true", "string", "number", "{", "+", "-"],
    "EXP": [";", "do", "then", "}", "<", "<=", "=", ">", ">=", "!=", "||"],
    "EXP'": [";", "do", "then", "}", "<", "<=", "=", ">", ">=", "!=", "||"],
    "ASIGN": [";"],
    "TERM": ["+", "-", ";", "do", "then", "}", "<", "<=", "=", ">", ">=", "!=", "||"],
    "TERM'": ["+", "-", ";", "do", "then", "}", "<", "<=", "=", ">", ">=", "!=", "||"],
    "FACTOR": ["+", "-", "*", "/", "&&", ";", "do", "then", "}", "<", "<=", "=", ">", ">=", "!=", "||"],
    "STATEMENTS": ["}", "endif"],
    "STATEMENTS'": ["}", "endif"],
    "FOR STAT": [";"],
    "CONTER": ["do"],
    "WHILE STAT": [";"],
    "INPUT": [";"],
    "ROS": ["}", ")"],
    "OUTPUT": [";"],
    "IF STAT": [";"],
    "ELSE": ["endif"],
    "ROT": [";", "do"]
  }